version: "3.9"

services:

  timescaledb:
    build:
      context: ./instrumented/timescaledb
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    ports:
      - 5999:5432/tcp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tsdb
      - POSTGRES_HOST_AUTH_METHOD=trust

  promscale:
    image: "timescale/promscale:latest"
    ports:
      - 9201:9201/tcp
      - 9202:9202/tcp
    restart: on-failure
    depends_on:
      - timescaledb
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_DB_URI: postgres://postgres:password@timescaledb:5432/tsdb?sslmode=allow

  jaeger:
    image: jaegertracing/jaeger-query:1.35
    ports:
      - 16685:16685/tcp
      - 16686:16686/tcp
      - 16687:16687/tcp
    restart: on-failure
    depends_on:
      - promscale
    environment:
      SPAN_STORAGE_TYPE: grpc-plugin
      GRPC_STORAGE_SERVER: promscale:9202

  grafana:
    build:
      context: ./instrumented/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    restart: on-failure
    depends_on:
      - timescaledb
      - jaeger

  collector:
    build:
      context: ./instrumented/collector
    ports:
      - 4317:4317/tcp
      - 4318:4318/tcp
    restart: on-failure
    depends_on:
      - promscale

  upper:
    build:
      context: ./instrumented/upper
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5054:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317

  lower:
    build:
      context: ./instrumented/lower
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5053:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318

  special:
    build:
      context: ./instrumented/special
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5052:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317
  
  digit:
    build:
      context: ./instrumented/digit
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5051:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317

  generator:
    build:
      context: ./instrumented/generator
    restart: on-failure
    depends_on:
      - upper
      - lower
      - special
      - digit
    ports:
      - 5050:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317

  load:
    build:
      context: ./instrumented/load
    restart: on-failure
    depends_on:
      - generator
    deploy:
      mode: replicated
      replicas: 3

volumes:
  timescaledb-data:
  grafana-data:
