apiVersion: v1
kind: Secret
metadata:
  name: tobs-promscale
type: Opaque
data:
  PROMSCALE_DB_USER: cG9zdGdyZXMK
  PROMSCALE_DB_PASSWORD: cGFzc3dvcmQK
  PROMSCALE_DB_HOST: dGltZXNjYWxlZGIK
  PROMSCALE_DB_NAME: b3RlbF9kZW1vCg==
