{
 "title": "03 Request Durations",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Distribution of Request Durations",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  start_time as time,\n  duration_ms\nFROM ps_trace.span\nWHERE $__timeFilter(start_time)\nAND parent_span_id is null\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Histogram of Request Durations",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT duration_ms\nFROM ps_trace.span\nWHERE $__timeFilter(start_time)\nAND parent_span_id is null"
    }
   ]
  },
  {
   "title": "Request Duration Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket('1 minute', start_time) as time,\n    ROUND(approx_percentile(0.99, percentile_agg(duration_ms))::numeric, 3) as duration_p99,\n    ROUND(approx_percentile(0.95, percentile_agg(duration_ms))::numeric, 3) as duration_p95,\n    ROUND(approx_percentile(0.90, percentile_agg(duration_ms))::numeric, 3) as duration_p90,\n    ROUND(approx_percentile(0.50, percentile_agg(duration_ms))::numeric, 3) as duration_p50\nFROM span\nWHERE\n    $__timeFilter(start_time)\n    AND parent_span_id is null\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Slowest Requests",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  replace(trace_id::text, '-'::text, ''::text) as trace_id,\n  start_time,\n  duration_ms\nFROM ps_trace.span\nWHERE $__timeFilter(start_time)\nAND parent_span_id is null\nORDER BY duration_ms DESC\nLIMIT 10\n;"
    }
   ]
  }
 ]
}