apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo
spec:
  exporter:
    endpoint: http://demo-collector:4318
  propagators:
  - tracecontext
  - baggage
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
