apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- persistentvolumeclaim.yaml
- service.yaml

configMapGenerator:
- name: timescaledb-bootstrap
  files:
  - 100_toolkit.sql
