receivers:
  otlp:
    protocols:
      grpc:
      http:

  # Dummy receiver that's never used, because a pipeline is required to have one.
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:12345"

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheusremotewrite
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"

exporters:
  otlp:
    endpoint: promscale:9202
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: "http://promscale:9201/write"
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics, batch]
      exporters: [otlp]

    metrics:
      # This receiver is just a dummy and never used.
      # Added to pass validation requiring at least one receiver in a pipeline.
      receivers: [otlp/spanmetrics]
      exporters: [prometheusremotewrite]
