{
 "title": "02 Error Rates",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "SELECT value#>>'{}'\nFROM _ps_trace.tag\nWHERE key = 'service.name'"
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": "SELECT DISTINCT span_name\nFROM _ps_trace.operation\nWHERE service_name_id IN\n(\n    SELECT id\n    FROM _ps_trace.tag\n    WHERE key = 'service.name'\n    AND value#>>'{}' IN (${service:sqlstring})\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Errors by Service",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    service_name,\n    count(*) as num_err\nFROM ps_trace.span\nWHERE $__timeFilter(start_time)\nAND status_code = 'STATUS_CODE_ERROR'\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    x.service_name,\n    x.span_name,\n    x.num_err::numeric / x.num_total as err_rate\nFROM\n(\n    SELECT\n        service_name,\n        span_name,\n        count(*) filter (where status_code = 'STATUS_CODE_ERROR') as num_err,\n        count(*) as num_total\n    FROM ps_trace.span\n    WHERE $__timeFilter(start_time)\n    AND (service_name IN (${service:sqlstring}))\n    AND (span_name IN (${operation:sqlstring}))\n    GROUP BY 1, 2\n) x\nORDER BY err_rate desc"
    }
   ]
  },
  {
   "title": "Error Rates by Minute",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n    x.time,\n    x.service_name,\n    x.span_name,\n    x.num_err::numeric / x.num_total as err_rate\nFROM\n(\n    SELECT\n        time_bucket('1 minute', start_time) as time,\n        service_name,\n        span_name,\n        count(*) filter (where status_code = 'STATUS_CODE_ERROR') as num_err,\n        count(*) as num_total\n    FROM ps_trace.span\n    WHERE $__timeFilter(start_time)\n    AND (service_name IN (${service:sqlstring}))\n    AND (span_name IN (${operation:sqlstring}))\n    GROUP BY 1, 2, 3\n) x\nORDER BY time"
    }
   ]
  }
 ]
}