apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: promscale
  name: promscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promscale
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: promscale
    spec:
      containers:
      - env:
        - name: PROMSCALE_DB_CONNECT_RETRIES
          value: "10"
        - name: PROMSCALE_DB_URI
          value: postgres://postgres:password@timescaledb:5432/tsdb?sslmode=allow
        image: timescale/promscale:latest
        name: promscale
        ports:
        - containerPort: 9201
        - containerPort: 9202
      restartPolicy: Always
