{
 "title": "08 Dashboard 1 Finished",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Slowest Traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    s.trace_id,\n    s.duration_ms\nFROM ps_trace.span s\nWHERE $__timeFilter(s.start_time) -- s.start_time > now() - interval '15 minutes'\nAND s.parent_span_id IS NULL -- only root spans\nORDER BY s.duration_ms DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Histogram of Latencies",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    s.trace_id,\n    s.duration_ms\nFROM ps_trace.span s\nWHERE $__timeFilter(s.start_time) -- s.start_time > now() - interval '15 minutes'\nAND s.parent_span_id IS NULL -- only root spans"
    }
   ]
  },
  {
   "title": "Number of Traces in Time Window",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as nbr_traces\nFROM ps_trace.span s\nWHERE $__timeFilter(s.start_time) -- s.start_time > now() - interval '15 minutes'\nAND s.parent_span_id IS NULL -- only root spans"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket('10 seconds', s.start_time) as time,\n    count(*) as nbr_traces\nFROM ps_trace.span s\nWHERE $__timeFilter(s.start_time) -- s.start_time > now() - interval '15 minutes'\nAND s.parent_span_id IS NULL -- only root spans\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "P95 Latencies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket('10 second', s.start_time) as time,\n    approx_percentile(0.95, percentile_agg(s.duration_ms)) as duration_p95\nFROM ps_trace.span s\nWHERE $__timeFilter(s.start_time)\nAND s.parent_span_id IS NULL\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Histogram of Latencies",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket('10 seconds', s.start_time) as time,\n    s.duration_ms\nFROM ps_trace.span s\nWHERE $__timeFilter(s.start_time)\nAND s.parent_span_id IS NULL"
    }
   ]
  },
  {
   "title": "Total Execution Time by Operation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket('10 seconds', s.start_time) as time,\n    s.service_name || ' ' || s.span_name as operation,\n    sum(\n        s.duration_ms -\n        coalesce(\n        (\n            -- the sum of the durations of the direct children\n            SELECT sum(k.duration_ms)\n            FROM ps_trace.span k\n            WHERE k.trace_id = s.trace_id\n            AND k.parent_span_id = s.span_id\n            AND $__timeFilter(k.start_time)\n        ), 0)\n    ) as total_exec_ms\nFROM ps_trace.span s\nWHERE $__timeFilter(s.start_time)\nGROUP BY time, s.service_name, s.span_name\nORDER BY time, total_exec_ms"
    }
   ]
  },
  {
   "title": "Execution Time by Operation",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    s.service_name || ' ' || s.span_name as operation,\n    sum(\n        s.duration_ms -\n        coalesce(\n        (\n            -- the sum of the durations of the direct children\n            SELECT sum(k.duration_ms)\n            FROM ps_trace.span k\n            WHERE k.trace_id = s.trace_id\n            AND k.parent_span_id = s.span_id\n            AND $__timeFilter(k.start_time)\n        ), 0)\n    ) as total_exec_ms\nFROM ps_trace.span s\nWHERE $__timeFilter(s.start_time)\nGROUP BY s.service_name, s.span_name"
    }
   ]
  },
  {
   "title": "Operation Durations",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n    x.service_name,\n    x.span_name,\n    avg(x.duration_ms) as avg_duration_ms,\n    approx_percentile(0.95, percentile_agg(x.duration_ms)) as duration_p95\nFROM\n(\n    SELECT\n        s.trace_id,\n        s.service_name,\n        s.span_name,\n        sum(\n            s.duration_ms -\n            coalesce(\n            (\n                -- the sum of the durations of the direct children\n                SELECT sum(k.duration_ms)\n                FROM ps_trace.span k\n                WHERE k.trace_id = s.trace_id\n                AND k.parent_span_id = s.span_id\n                AND $__timeFilter(k.start_time)\n            ), 0)\n        ) as duration_ms\n    FROM ps_trace.span s\n    WHERE $__timeFilter(s.start_time)\n    GROUP BY s.trace_id, s.service_name, s.span_name\n) x\nGROUP BY x.service_name, x.span_name\nORDER BY 4 DESC"
    }
   ]
  }
 ]
}