name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run-demo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test demo example
      run: docker-compose up --remove-orphans --build --detach
      
